version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    container_name: covidform
    restart: on-failure
    ports:
      - $PORT:$PORT
    env_file:
      - .env
